packages:
  - 'packages/*'

# common dependencies
catalog:
  typescript: ^5.8.3
  # document generator
  typedoc: ^0.28.3
  # builder tool
  tsup: ^8.4.0
  # vitest
  vitest: ^3.1.2
  "@vitest/coverage-v8": ^3.1.2
  "@vitest/ui": ^3.1.2
  # depended on by vitest
  zod: ^3.24.3

# specific dependencies
catalogs:
  esmodules:
    # depended on by vitest
    jsdom: ^26.1.0
  commonjs:
    "@types/node":  ^22.15.3
