packages:
  - 'packages/*'

# common dependencies
catalog:
  typescript: ^5.8.3
  # document generator
  typedoc: ^0.28.3
  # builder tool
  tsup: ^8.4.0
  # vitest
  vitest: ^3.1.2
  "@vitest/coverage-v8": ^3.1.2
  "@vitest/ui": ^3.1.2
  # depended on by vitest
  zod: ^3.24.3

# specific dependencies
catalogs:
  esmodules:
    # depended on by vitest
    happy-dom: ^17.4.6
  commonjs:
    "@types/node":  ^22.15.3
  examples:
    # filelist & browser
    react: ^19.0.0
    react-dom: ^19.0.0
    "@eslint/js": ^9.22.0
    "@types/react": ^19.0.10
    "@types/react-dom": ^19.0.4
    "@vitejs/plugin-react-swc": ^3.8.0
    eslint: ^9.22.0
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.19
    globals: ^16.0.0
    typescript-eslint: ^8.26.1
    vite: ^6.3.1
    "@hookform/error-message": ^2.0.1
    "@hookform/resolvers": ^5.0.1
    filepond: ^4.32.7
    filepond-plugin-image-exif-orientation: ^1.0.11
    filepond-plugin-image-preview: ^4.6.12
    react-filepond: ^7.1.3
    react-hook-form: ^7.56.1
    styled-components: ^6.1.17
