name: test/filelist

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      # Package Test (@mock-filelist/filelist)
      - name: Package Test (@mock-filelist/filelist)
        run: nix develop --command bash -c "pnpm i && pnpm run test:filelist"
      # Build Package (@mock-filelist/filelist)
      - name: Build Package (@mock-filelist/filelist)
        run: nix develop --command bash -c "pnpm i && pnpm run build:filelist"
      # @mock-filelist/filelist Example Test
      - name: Example Test (@mock-filelist/filelist)
        run: nix develop --command bash -c "pnpm i && pnpm run filelist-example:test"
