name: filelist-test

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      # Test (@mock-filelist/core)
      - name: Test (@mock-filelist/core)
        run: nix develop --command bash -c "pnpm i && pnpm run test:core"
      # Test (@mock-filelist/filelist)
      - name: Test (@mock-filelist/filelist)
        run: nix develop --command bash -c "pnpm i && pnpm run test:filelist"
