name: test/node

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      # Test (@mock-filelist/node)
      - name: Test (@mock-filelist/node)
        run: nix develop --command bash -c "pnpm i && pnpm run test:node"
      # Build Package (@mock-filelist/node)
      - name: Build Package (@mock-filelist/node)
        run: nix develop --command bash -c "pnpm i && pnpm run build:node"
      # @mock-filelist/node Example Test
      - name: Example Test (@mock-filelist/node)
        run: nix develop --command bash -c "pnpm i && pnpm run node-example:test"
